/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JOptionPane;
import models.Student;
import models.Tutor;
import tutoring.ControllerHelper;
import tutoring.ControllerHelper.MyException;

/**
 *
 * @author GrantSkalski
 */
public class UpdateReport extends javax.swing.JDialog {

    static class reportException extends Exception {

        reportException(String message) {
            super(message);
        }
    }

    
    
    public void setReportText(String text) {
        report.setText(text);
    }
    
    public String getReportText(){
        return report.getText();
    }

    public void addUpdateReportActionListener(ActionListener listener) {
        update.addActionListener(listener);
    }

    public void addCancelActionListener(ActionListener listener) {
        cancel.addActionListener(listener);
    }

    /**
     * Creates new form UpdateReport
     */
    public UpdateReport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        report = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        report.setColumns(20);
        report.setRows(5);
        jScrollPane1.setViewportView(report);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        update.setText("Update");
        jPanel1.add(update);

        cancel.setText("Cancel");
        jPanel1.add(cancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea report;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
